apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/odhigboisaac/spring-boot-app.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD  # For Helm, this refers to the chart version.
    path: spring-boot-app # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

  # Destination cluster and namespace to deploy the application
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc
    # or cluster name
    # name: in-cluster
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: springmyapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
     selfHeal: true
     prune: true

